spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.profiles.active=jdbc
spring.datasource.url=jdbc:h2:mem:f1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=none
