spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.datasource.url=jdbc:postgresql:pro3_db
spring.datasource.username=postgres
spring.datasource.password=Student_1234
spring.jpa.hibernate.ddl-auto=update
