spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5050/f1Management
spring.datasource.username=spring
spring.datasource.password=spring
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.mode=always

